name: emimechanicalmodel
channels:
  - conda-forge
  - defaults
dependencies:
    - python
    - fenics
    - scipy
    - numpy
    - matplotlib
    - mpi4py
    - salib
    - pip:
      - git+https://github.com/aashildte/virtualss
