# Simple workflow for deploying static content to GitHub Pages
name: Unit tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: emimechanicalmodel
          environment-file: ./environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Install dependencies and build docs
        run: |
          pip install pytest
          pip install .

      - name: Run tests
        run:
          pytest .
